- hosts: all
  become: yes
  tasks:
    - name: Deploy Prometheus
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'prometheus.yaml') }}"

    - name: Deploy Grafana
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'grafana.yaml') }}"

