apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-node
  labels:
    app: ethereum-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ethereum-node
  template:
    metadata:
      labels:
        app: ethereum-node
    spec:
      containers:
      - name: ethereum
        image: ethereum/client-go:stable
        args:
          - "--networkid=15"
          - "--nodiscover"
          - "--http"
          - "--http.addr=0.0.0.0"
          - "--http.api=personal,db,eth,net,web3"
        ports:
        - containerPort: 8545
        - containerPort: 30303
        volumeMounts:
        - name: eth-data
          mountPath: /root/.ethereum
      volumes:
      - name: eth-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-node-service
spec:
  type: LoadBalancer
  ports:
    - port: 8545
      targetPort: 8545
  selector:
    app: ethereum-node
