apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum-genesis-config
  namespace: ethereum
data:
  genesis.json: |
    {
      "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "mergeNets": []
      "difficulty": "0x20000",
      "gasLimit": "0x8000000",
      "alloc": {},
      "extraData": "0x",
      "nonce": "0x0000000000000042"
    }
