apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-config
data:
  genesis.json: |
    {
      "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0
      },
      "difficulty": "200000000",
      "gasLimit": "2100000",
      "alloc": {}
    }
